name: ci-test

on:
  push:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

   services:
    postgres:
      image: postgres:14.4-alpine 
      env:
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: root
        POSTGRES_DB: simple_bank
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 3

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@2

    - name: Install golang-migrate
      run: |
        go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@4.15.2
        which migrate

    - name: Run migrations
      run: ./scripts.bash migrateup

    - name: Test
      run: ./scripts.bash test

