name: Deploy to production

on:
  push:
    branches: [main]

env:
  ACR_REGISTRY: workbenchdpsigor.azurecr.io
  ACR_REPOSITORY: golangcheatsheet

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build, tag and deploy to Azure ACR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker login -u ${{ secrets.ACR_USERNAME }} -p "${{ secrets.ACR_PASSWORD }}" $ACR_REGISTRY
          docker build -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG .
          docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
